# Generated by Django 3.2 on 2021-04-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210421_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
